name: Security Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Syft
      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Syft
        run: syft . -o table

      # Semgrep
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=auto .

           # Gitleaks
      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.10.0/gitleaks-linux-amd64-v8.10.0.tar.gz -o gitleaks.tar.gz
          tar -xvzf gitleaks.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin


      - name: Run Gitleaks
        run: gitleaks detect --source=. --report-format sarif --report-path=gitleaks.sarif

      # Start Juice Shop before ZAP scan
      - name: Start Juice Shop
        run: docker run -d -p 3000:3000 bkimminich/juice-shop

      - name: Wait for Juice Shop to be ready
        run: sleep 15

      # OWASP ZAP
      - name: Run ZAP
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'
