name: Security Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Syft
      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Syft
        run: syft . -o table

      # Semgrep
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=auto .

  secret-scan:
    name: GitLeaks - Sır Taraması
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu Kontrol Et
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitLeaks ile Sızıntı Taraması
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  zap:
    name: OWASP ZAP Taraması
    runs-on: ubuntu-latest
    steps:
      - name: Start Juice Shop
        run: docker run -d -p 3000:3000 bkimminich/juice-shop

      - name: Wait for Juice Shop to be ready
        run: sleep 15

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'
