name: Security Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Syft
      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Syft
        run: syft . -o table

      # Semgrep
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=auto .

      # Gitleaks
      - name: Install Gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/main/install.sh | bash
          sudo mv gitleaks /usr/local/bin

      - name: Run Gitleaks
        run: gitleaks detect --source=. --report-format sarif --report-path=gitleaks.sarif

      # OWASP ZAP
      - name: Run ZAP
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'

